Updated `Microsoft.Storage/storageAccounts` to `2023-05-01`
CompositionalIT/farmer pull request #1144
Opened 2024-10-24 20:36 UTC by xperiandri

Implemented:
* `ImmutableStorageWithVersioning`
* `RequireInfrastructureEncryption`This PR closes #

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [X] **Tested my code** end-to-end against a live Azure subscription.
* [X] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [X] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [X] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:
Which test would you recommend to modify or implement?

Below is a minimal example configuration that includes the new features, which can be used to deploy to Azure:

```fsharp
let storage = storageAccount {
    name "wormtest222"
    sku Farmer.Storage.Sku.Standard_GRS
    disable_blob_public_access
    add_private_container
        "container"
        (blobContainerImmutabilityPolicies {
            allow_protected_append_writes AllAppendAllowed
            immutability_period_since_creation (365<Days> * 5)
        })
}

```

2024-10-25 17:44 UTC, xperiandri commented
@ninjarobot do you have any remarks?

2024-10-25 17:45 UTC, xperiandri commented on src/Farmer/Arm/Storage.fs
> +                    supportsHttpsTrafficOnly = this.SupportsHttpsTrafficOnly.AsBoolean()
I ordered them by name as otherwise it is hard to compare to the specification

2024-10-26 18:03 UTC, isaacabraham commented
You want to write at least one test confirmation the JSON that is emitted in the generate ARM template is correct i.e. checking fields etc.

2024-10-26 18:06 UTC, isaacabraham commented
From an API design, what happens if you don't want to set any policies - do you need to provide a policy regardless (bear in mind computation expressions don't allow optional arguments AFAIK, and overloads must all have the same number of arguments)? I think perhaps creating a dedicated `container { }` CE which can have members on it including e.g.:

* `name`
* `accessibility` (public / private)
* `immutability_policy`

would be a better way to go.

2024-10-26 18:28 UTC, isaacabraham commented
Also can you make an issue first which clearly outlines what this PR is designed to solve - normally we create issues, get them approved, and then create a PR to resolve them (in that order :-))

2024-10-27 14:56 UTC, isaacabraham requested changes
Before merging, we need to modify the API - the use of a CE in this regard isn't going to work, from what I can see, from a usability perspective.

2024-10-27 15:26 UTC, xperiandri commented on src/Farmer/Builders/Builders.Storage.fs
> +                ImmutableStorageWithVersioning = None // TODO: Implement
@ninjarobot I mean here that there is not such operation in the builder. That is what needs to be implemented

2024-10-27 15:28 UTC, xperiandri commented on src/Farmer/Builders/Builders.Storage.fs
> +                            ((StorageResourceName.Create name).OkValue, access, immutabilityPolicies))
I completely agree. I've missed that accidsentially

2024-10-27 15:31 UTC, xperiandri commented
> From an API design, what happens if you don't want to set any policies - do you need to provide a policy regardless (bear in mind computation expressions don't allow optional arguments AFAIK, and overloads must all have the same number of arguments)?

@isaacabraham, actually it works fine as all the tests pass. I verified that it works both ways and allow that optional parameter to be specified and omitted

2024-10-27 18:59 UTC, isaacabraham commented
> @isaacabraham, actually it works fine as all the tests pass. I verified that it works both ways and allow that optional parameter to be specified and omitted

That's good :-) Nonetheless, I think moving to a dedicated `container { }` CE at this stage makes more sense.

This PR still needs tests for the new code that's been created as well as the other points mentioned (including an issue / issues that reflect the actual changes that are being made here - it's not so much about upgrading the versions but about immutable blobs etc.).

Happy to talk through with you the API choices and anything else that's needed.

2024-10-27 19:35 UTC, xperiandri commented
I thought about that but considered immutable policy as not so big change to introduce container CE.
However further container customization support may need a CE

2024-10-28 17:44 UTC, xperiandri commented
I've implemented tests. Let me know if I miss something

2024-10-28 19:18 UTC, xperiandri commented
> Before merging, we need to modify the API - the use of a CE in this regard isn't going to work, from what I can see, from a usability perspective.

@isaacabraham my idea was to add now and preserve in the future ability to specify immutability policy
And add `blobContainer` CE and operations to `storageAccount` CE accepting `BlobContainerConfig` along with supporting additional container settings.
I have no intent to add them right now as it widens the scope of this PR.
Do you think `blobContainer` should be coupled with these changes?

2024-10-31 00:43 UTC, isaacabraham commented
I think so, yes. If you look elsewhere in the Farmer API, you won't really much in the way of CEs being supplied as secondary arguments to a custom keyword, and I really would like to retain the pattern that we have.

You can repurpose the CE you've already built to actually be the container one - just add in the extra name parameter. You can then add that as an overload for the top-level CE `add_private_container` member.

What do you think?

Thanks for adding the tests.

2024-11-15 14:52 UTC, xperiandri commented
@isaacabraham I've implemented `storageBlobContainer` CE as you suggested.
Any other remarks?

2025-03-12 19:04 UTC, xperiandri commented
I’ve done all the requested changes

2025-03-14 15:30 UTC, mattgallagher92 reviewed
Thanks for your contribution @xperiandri and sorry for the delay - Isaac has been indisposed recently

I'm happy with the changes in principle, though have a few small queries in review comments.

2025-03-14 15:30 UTC, mattgallagher92 commented on src/Farmer/Arm/Storage.fs
> +                        |})
Using `this.RequireInfrastructureEncryption` inside the `map` seems weird! The behaviour is essentially this:

```fs
                        match this.RequireInfrastructureEncryption with
                        | Some true -> Some {| requireInfrastructureEncryption = Some true |}
                        | Some false -> Some {| requireInfrastructureEncryption = Some false |}
                        | None -> None
```

I might actually prefer that way of expressing it (I think it's a bit clearer), but presumably the `Some` is erased when we go to JSON, so we could simplify to this:

```suggestion
                        this.RequireInfrastructureEncryption
                        |> Option.map (fun b -> {| requireInfrastructureEncryption = b |})
```

Let me know if I'm wrong!

2025-03-14 15:30 UTC, mattgallagher92 commented on src/Farmer/Builders/Builders.Storage.fs
> +                ImmutableStorageWithVersioning = None // TODO: Implement
Let's use GitHub issues rather than TODO comments to track possible enhancements. Would you mind creating one @xperiandri?

2025-03-14 15:30 UTC, mattgallagher92 commented on src/Farmer/Builders/Builders.Storage.fs
> +    member _.Name(state: StorageBlobContainerConfig, metadata: (string * string) list) =
```suggestion
    member _.Metadata(state: StorageBlobContainerConfig, metadata: (string * string) list) =
```

2025-03-14 15:30 UTC, mattgallagher92 commented on src/Farmer/Arm/Storage.fs
> +                identity = None // TODO: user assigned identity
I see from other discussions that perhaps it's for later enhancements. Let's use GitHub issues in that case.

2025-03-14 16:53 UTC, xperiandri commented on src/Farmer/Arm/Storage.fs
> +                identity = None // TODO: user assigned identity
If you prefer I can remove that however I would leave that

2025-03-14 20:02 UTC, xperiandri commented on src/Farmer/Arm/Storage.fs
> +    /// When enabled, new blocks can be written to both 'Append and Bock Blobs' while maintaining immutability protection and compliance. Only new blocks can be added and any existing blocks cannot b
As far as I remember I copied that from official docs but we can modify this a bit as you suggested

2025-03-21 12:49 UTC, mattgallagher92 commented on src/Tests/Storage.fs
> +                        add_blob_containers [
@xperiandri should the containers be used in assertions? If not, what's the point of adding them here?

2025-03-21 13:01 UTC, mattgallagher92 commented
@xperiandri I've looked at the parts where you had TODOs in more depth based on `ImmutableStorageWithVersioning`. I see that there are two cases:

- The `immutableStorageWithVersioning` field in the ARM template has a representation in the `StorageAccount` type that implements `IArmResource`, which affects the generated JSON. However there is no corresponding configuration available in the builder, and no test that the generated JSON is correct.
 - The `extendedLocation` and `identity` fields will always be set to null in the generated JSON.

I have a few questions:

- Why did you add them if they're not used? Are the fields required in the ARM template JSON?
- If not, why not just leave them out of the Farmer codebase altogether?
- Why have you made `immutableStorageWithVersioning` configurable via the F# type but not done the same for `extendedLocation` and `identity`?

2025-03-21 13:06 UTC, xperiandri commented
> Why did you add them if they're not used? Are the fields required in the ARM template JSON?

Not required, just to mark they exist but not implemented

> If not, why not just leave them out of the Farmer codebase altogether?

I can if you prefer

> Why have you made `immutableStorageWithVersioning` configurable via the F# type but not done the same for `extendedLocation` and `identity`

I only implemented the piece I need and the scope defined by the PR name

2025-03-21 15:19 UTC, mattgallagher92 commented
> > Why have you made immutableStorageWithVersioning configurable via the F# type but not done the same for extendedLocation and identity
>
> I only implemented the piece I need and the scope defined by the PR name

So you're using it directly on the `Farmer.Arm.Storage.StorageAccount` type rather than via the computation expression?

2025-03-21 20:19 UTC, xperiandri commented on src/Farmer/Builders/Builders.Storage.fs
> +    }
> So you're using it directly on the Farmer.Arm.Storage.StorageAccount type rather than via the computation expression?

@mattgallagher92 no, here is the builder

2025-03-29 11:52 UTC, xperiandri commented on src/Farmer/Builders/Builders.Storage.fs
> +    }
I still have not got what your question is about.
Isaak asked to create a container CE.
I need immutability policies, so I also created CE for them.
So now we have blob container and blob container immutability policies CEs, and corresponding properties for them within the `StorageAccount` record.

Could you describe again what inconsistency you have found?

2025-04-04 17:13 UTC, mattgallagher92 commented on src/Farmer/Builders/Builders.Storage.fs
> +    }
Sure 🙂 Thanks for your patience and sorry that this is dragging on so long. I don't have a lot of time available to review this (and unfortunately I'm going to be unavailable over the next few weeks).

When I search for references to the `ImmutableStorageWithVersioning` property on `Farmer.Arm.Storage.StorageAccount`, I see that it's used in 4 places. 3 of those places set it to `None`, and the remaining place uses it via `Option.map`, which will therefore also always return `None`. As far as I can see, there doesn't seem to be any means of setting it to anything other than `None` via a builder, so it seems to be that the `Option.map` code is not being tested and is perhaps even redundant.

Given it doesn't seem to be possible to set it via builder, I wondered whether you were setting the field directly on the record somehow, or whether this is something that you don't need.

2025-06-13 13:40 UTC, mattgallagher92 commented on src/Farmer/Builders/Builders.Storage.fs
> +    }
@xperiandri I see a commit labelled `Implemented storage account level immutability policy setting and builder`, but I don't actually see the implementation in the diff?

2025-06-13 13:46 UTC, mattgallagher92 commented
@xperiandri I've re-reviewed. The unresolved conversations are the things that have not been addressed.

Note for other maintainers: I'm leaving Compositional IT, so I'm not going to be able to re-review this. There are a few unresolved conversations, but I think that this is good enough to go in as it is. Hopefully Andrii can easily add the missing builder implementation that is mentioned in the latest commit message (e0e6cea2de3f6e06fc8ff4b79a6bf2631a0b3390), but not actually present in the diff. Once that's done, the other changes are minor ones that maintainers can make before merging.

If preferred for whatever reason, I think that it would be reasonable to merge the code as is and make the outstanding tweaks later - the code is good enough.

2025-06-13 15:30 UTC, closed without merging

2025-06-13 16:02 UTC, xperiandri commented
I thought I have finally implemented all the builders