Add  Log Analytics
CompositionalIT/farmer pull request #399
Opened 2020-10-08 13:25 UTC by MoeJw

This PR closes issue #262

The changes in this PR are as follows:

* ...
* ...
* ...

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [ ] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [ ] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [ ] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

2020-10-09 08:17 UTC, isaacabraham requested changes
Mostly just some formatting changes. The only real code change I would suggest is around the pattern match.

2020-10-09 08:17 UTC, isaacabraham commented on src/Tests/Helpers.fs
> +//convertResourceBuilder ()(LogAnalytics)
Remove commented out code.

2020-10-09 08:17 UTC, isaacabraham commented on src/Tests/LogAnalytics.fs
> +
Remove unnecessary whitespace / blank lines after each of the tests.

2020-10-09 08:17 UTC, isaacabraham commented on src/Tests/LogAnalytics.fs
> +    Expect.throws (fun _ -> ( d.BuildResources Location.WestEurope |>ignore)) ""
Should have a space after `|>`.

2020-10-09 08:17 UTC, isaacabraham commented on src/Tests/LogAnalytics.fs
> +    Expect.throws (fun _ -> ( d.BuildResources Location.WestEurope |>ignore)) ""
No space after parenthesis e.g. `(c.BuildResources...`).

2020-10-09 08:17 UTC, isaacabraham commented on src/Tests/LogAnalytics.fs
> +                                 } :> IBuilder
Align closing `}` with the opening one.

2020-10-09 08:17 UTC, isaacabraham commented on src/Farmer/Builders/Builders.LogAnalytics.fs
> +
Remove whitespace line.

2020-10-09 08:17 UTC, isaacabraham commented on src/Farmer/Builders/Builders.LogAnalytics.fs
> +        {   Name = ResourceName.Empty
Just one space between `{` and `Name` please.

2020-10-09 08:17 UTC, isaacabraham commented on src/Farmer/Builders/Builders.LogAnalytics.fs
> +                    match this.retentionInDays with
reformat to standard F# guidelines e.g.

```fsharp
match this.retentionInDays with
| Standard when value <> 30 -> ...
| Premium when value <> 365 -> ...
```

etc.

2020-10-09 08:17 UTC, isaacabraham commented on src/Farmer/Builders/Builders.LogAnalytics.fs
> +                                |Premium    when  value<>365 -> failwithf "the retention Days for Premium must be 365."
Consider flipping the match to a tupled match to remove the need for `when` clauses e.g.

```fsharp
match this.Sku, this.RetentionInDays with
| Standard, Some 30 -> ...
| Standard, Some _ -> failwith "must be 30 days"
```

etc.

2020-10-09 08:17 UTC, isaacabraham commented on samples/scripts/loganalytics.fsx
> +      }
Align closing brace per other samples.

2020-10-09 08:17 UTC, isaacabraham commented on samples/scripts/keyvault.fsx
> -#r @"../../src/Farmer/bin/Debug/netstandard2.0/Farmer.dll"
In this updated path correct?

2020-10-09 08:17 UTC, isaacabraham commented on Farmer.sln
> -Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "Tests", "src\Tests\Tests.fsproj", "{D68F5B81-6F18-4FC7-B9FD-2113EE7614CE}"
Is there a reason for this file to change?

2020-10-09 08:18 UTC, isaacabraham commented
Thank you very much :-) Completed a review on this - mostly just aesthetic changes required.

2020-10-11 20:35 UTC, MoeJw commented
Thanks for your attention. I look forward to doing more

2020-10-13 23:27 UTC, isaacabraham commented
@MoeJw Have you tested this out end-to-end (as in, deployed a workspace using this)?

2020-10-13 23:42 UTC, isaacabraham commented
Where are the rules coming from regarding retention period? Looking at the official ARM specs, it [simply says](https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces#workspaceproperties-object:

> The workspace data retention in days. -1 means Unlimited retention for the Unlimited Sku. 730 days is the maximum allowed for all other Skus.

Terraform goes a [little further](https://www.terraform.io/docs/providers/azurerm/r/log_analytics_workspace.html):

> retention_in_days - (Optional) The workspace data retention in days. Possible values are either 7 (Free Tier only) or range between 30 and 730.

Where is the reference to these rules:

* Standard must be 30
* Premium must be 365
* Free must not be set

2020-10-14 00:35 UTC, isaacabraham commented
Looking at the SKUs a little more, I am currently of the opinion that we should only support the new pricing PerGB2018 pricing tier plus capacity reservation options.

2020-10-14 11:21 UTC, MoeJw commented
> Where are the rules coming from regarding retention period? Looking at the official ARM specs, it [simply says]

Yes, that's what I did first I tried to follow their specs and tested it by deploying it on Azure. 
I tried different scenarios but there was something wrong with it

![image](https://user-images.githubusercontent.com/42002662/95971678-32d9b880-0e1a-11eb-8edc-29d02d1483ba.png)

I found out later about this article describing  the azure Manage usage and costs with Azure Monitor Logs
[https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-cost-storage#change-the-data-retention-period](url)

>Workspaces in the Standalone or Per Node pricing tiers have user-configurable retention from 30 to 730 days.

> the original Standard and Premium pricing tiers which have fixed data retention of 30 and 365 days respectively.

I tested these as described on Azure  and it worked
- Standard 30
- Premium  365
- Standalone, Per Node and PerGB 30-730

> If you specify a pricing tier of Free, then remove the retentionInDays element.
[https://docs.microsoft.com/en-us/azure/azure-monitor/samples/resource-manager-workspace](url)

but here is the thing Standard, Premium, Standalone, and Per Node (OMS)  these are all legacy pricing tiers
so if you try to create LogAnalytics on Azure portal the only option provided is PerGB
however, you can  still use these legacy tiers when you deploy them as an arm template (:

**here is an example when you try to create log analytics on Azure portal** 

![image](https://user-images.githubusercontent.com/42002662/95978570-09715a80-0e23-11eb-8e2b-d54b7e57fa96.png)

I was confused a little bit about it so I decided that I will leave it for the user to choose. but my guess now we should only support the new pricing PerGB2018

2020-10-14 11:39 UTC, isaacabraham commented
@MoeJw I've updated the PR with a set of changes I made yesterday. Most of them were around code style and clean up - I'd suggest looking through them as it provides a good example of the coding style and standards for the project for future reference.

I also made some changes to the way we model SDK and Retention Period - instead of leaving them as two separate fields, we now model the relationship between them, which removes the need for much of the validation because it's now impossible to create e.g. Standard with a Retention Period at all.

I tested it out for both the Per GB and at least one legacy option. The UI in the portal doesn't offer the legacy options any more, unless you have created a resource using a legacy SKU. For that reason I think we should avoid providing them; if we end up just going with the new PerGB model the model can be simplified further.

I also noticed some undocumented features on the ARM template that are available in the UI. There's also no documentation that I could find on the Capacity Reservation options. @alex-frankel do you have any idea if there is any up-to-date docs on the Log Analytics resource - [this link](https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces) is pretty out of date:

* It references something called the Unlimited Sku which doesn't even exist.
* No documentation on how to specify capacity reservation
* Daily Cap is available in the UI but not mentioned here. Exporting a template shows the following as a property:

```json
"workspaceCapping": {
    "dailyQuotaGb": 1
}
```

but this is not mentioned in the specs.

2020-10-14 11:49 UTC, MoeJw reviewed
can we use a tool like fantomas for formating?

2020-10-14 11:51 UTC, MoeJw commented
> @MoeJw I've updated the PR with a set of changes I made yesterday. Most of them were around code style and clean up - I'd suggest looking through them as it provides a good example of the coding style and standards for the project for future reference.

Thank you so much, I will try to follow the standards next time sorry

2020-10-14 12:02 UTC, isaacabraham commented
@MoeJw no worries - I'm really grateful that you've taken the time to get involved, it's a new codebase etc. and I'm happy to help out :-)

2020-10-14 12:03 UTC, isaacabraham commented
There's actually an issue about fantomas that's already been opened - I should really look into that.

2020-10-14 12:15 UTC, MoeJw commented
any Further changes requested for this PR  ?

2020-10-14 12:28 UTC, isaacabraham commented
@MoeJw I think it's now at a state where it's ready to go. I'm just waiting to hear from Alex regarding the questions above; the only change we might make is removing the SKU type completely and just leaving it as the PerGB one, which would mean removing the sdk keyword and re-introducing the retention_period one.

2020-10-14 17:33 UTC, alex-frankel commented
Sent an email that you are cc'd on @isaacabraham 

Unfortunately, I don't know the answers. That being said, my position would be is if it is *possible* via the PUT API, it should be supported in Farmer because someone may need those properties -- even if they are not documented. I can understand wanting to hide them though.

2020-10-14 18:05 UTC, isaacabraham commented
@alex-frankel thanks again for looping me in.

The daily cap is something that's exposed in the UI and *appears* to get emitted by the portal-generated template. With the other stuff, it just looks like the documentation is incomplete - the docs refer to the capacity reservation but don't say anything about how to actually use it :-)

2020-10-15 00:03 UTC, isaacabraham approved these changes

2020-10-15 00:04 UTC, isaacabraham commented
@MoeJw I can see you've checked that you've updated the release notes but I can't find the update there?

2020-10-15 00:13 UTC, isaacabraham commented
Also I've updated the docs with my changes but I think that there are a few elements still missing like Tags. If you could just add those, I can then merge this in.

2020-10-15 09:35 UTC, MoeJw commented
@isaacabraham  yeah I think the only thing left in docs is Tags.

2020-10-15 21:45 UTC, merged