#434 add premium V3,
CompositionalIT/farmer pull request #436
Opened 2020-10-28 07:45 UTC by MNie

- update cognitive services SKU

This PR closes #434

The changes in this PR are as follows:

* Add premiumV3 to WebApp
* Add S5/S6/S7/S8 for CognitiveServices

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [X] **Updated the documentation** in the docs folder for the affected changes.
* [X] **Written unit tests** against the modified code that I have made.
* [X] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [X] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

CC: @isaacabraham 

I saw that we don't give an ability to select S5/S6/S7/S8 for Bing.Search as noted [here](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/resourceskus/list). I add this option but I also include a validation regarding the kind & sku because S5/S6/S7/S8 are available only for Bing.Search.

I also update the plans for WebApp in the same PR.

Questions I have:
- Is it okay to do it in a single PR or should I create separate PRs?
- Validation for kind & sku seems reasonable or we don't want to do this?

Because of the above questions, I created the PR as a draft.

2020-10-28 20:07 UTC, isaacabraham requested changes

2020-10-28 20:07 UTC, isaacabraham commented on src/Tests/CognitiveServices.fs
> +let casesForSkuLessThanPremium =
Formatting, start / end lists should be as follows:

```fsharp
let x = [
    ...
    ...
]

2020-10-28 20:07 UTC, isaacabraham commented on src/Farmer/Common.fs
> +                yield
`yield` keyword is obsolete.

2020-10-28 20:08 UTC, isaacabraham commented
Great questions. I think on reflection it would be better to do the Cognitive Services stuff as a separate PR please.

Happy to merge in the App Service stuff, as long as you can spin up an instance for the new sku to prove it works (I'm sure if you're quick it won't cost more than 2 or 3 cents ;-))

2020-11-02 07:22 UTC, MNie commented
@isaacabraham I extracted Cognitive services changes as a separate PR: #440 should I create also an Issue for that?

2020-11-03 22:31 UTC, isaacabraham commented
Any chance that you can do an end-to-end test of this please?

2020-11-18 23:22 UTC, isaacabraham commented
@MNie happy to merge this in once you've done an end-to-end on this.

2021-01-13 01:23 UTC, daniellittledev commented
Are we just waiting on the  end-to-end test for this PR?

2021-01-13 10:27 UTC, isaacabraham commented
@daniellittledev basically, yes.

2021-01-28 19:46 UTC, merged

2021-01-28 19:47 UTC, isaacabraham commented
Thanks for this!