Add Support for nested resource groups
CompositionalIT/farmer pull request #621
Opened 2021-04-30 09:08 UTC by TheRSP

This PR closes #457 
This PR provides the basis for further work on #215

The changes in this PR are as follows:

* Refactored ArmBuilder into a ResourceGroupBuilder following the normal Arm/Builder conventions
* Added `resourceGroup` keyword and `arm` alias for backwards compatibility

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [x] **Written unit tests** against the modified code that I have made.
* [ ] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [ ] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

2021-04-30 11:00 UTC, TheRSP commented
@isaacabraham @ninjarobot this PR replaces !466
While it doesn't support subscription-scoped deployments it is a much smaller change which allows for deploying nested templates. This is a really useful feature for:
1. Deploying my resources and updating some share resource
2. Resolving some circular dependencies in deployments (e.g. webApp/cert depends on hostnameBinding but hostnameBinding needs to reference cert thumbprint) by allowing you to perform multiple deployments in one (e.g. deploy some resources then update some of them)

2021-05-21 08:01 UTC, TheRSP commented
I have added an additional test focussing directly on the copying of parameters from the outer template.
Here is a sample farmer script and simplified, annotated output showing how this works
Farmer:
```fsharp
let nested = resourceGroup {
    name "farmer-deploy"
    location Location.UKSouth
    add_resource (vm {
        name "farmer-test-vm"
        username "the-boss-man"
        vm_size Vm.VMSize.Standard_A1_v2
        })
}
let deployment = arm {
    location Location.UKSouth
    add_resource nested
}
```
ARM:
```jsonc
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "outputs": {},
  "parameters": {
    // Define parameters for outer template. These are taken from the inner template (and any other resources in the deployment)
    "password-for-farmer-test-vm": {
      "type": "securestring"
    }
  },
  "resources": [
    {
      "apiVersion": "2020-10-01",
      "dependsOn": [],
      "name": "farmer-deploy",
      "properties": {
        "expressionEvaluationOptions": {
          "scope": "Inner"
        },
        "mode": "Incremental",
        "parameters": {
          // Copy selected parameters from outer deployment to inner deployment
          "password-for-farmer-test-vm": {
            "value": "[parameters('password-for-farmer-test-vm')]"
          }
        },
        "template": {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "outputs": {},
          "parameters": {
            // Define parameters for inner template
            "password-for-farmer-test-vm": {
              "type": "securestring"
            }
          },
          "resources": [
            {
              "apiVersion": "2018-10-01",
              "dependsOn": [
                "[resourceId('Microsoft.Network/networkInterfaces', 'farmer-test-vm-nic')]"
              ],
              "location": "uksouth",
              "name": "farmer-test-vm",
              // ...
              "type": "Microsoft.Compute/virtualMachines"
            }
            // ...
          ]
        }
      },
      "resourceGroup": "farmer-deploy",
      "tags": {},
      "type": "Microsoft.Resources/deployments"
    }
  ]
}
```

2021-06-06 14:24 UTC, isaacabraham requested changes
In principle this looks very thorough and good to go, bar a couple of minor tweaks I've added here.

Let's get this merged into the main branch with a view to going into 1.6.

2021-06-06 14:24 UTC, isaacabraham commented on src/Farmer/Aliases.fs
> +let arm = Farmer.Builders.ResourceGroup.resourceGroup
Love it.

2021-06-06 14:24 UTC, isaacabraham commented on src/Farmer/Deploy.fs
> +let validateParameters suppliedParameters (deployment:#IDeploymentSource) =
Is there a reason why we're using flexible types here (i.e. `#IDeploymentSource` instead of just `IDeploymentSource`)? I'm not sure it's required.

2021-06-06 14:24 UTC, isaacabraham commented on src/Farmer/Deploy.fs
> +let validateParameters suppliedParameters (deployment:#IDeploymentSource) =
This applies for all cases this file.

2021-06-06 14:31 UTC, isaacabraham commented
I've tried to make a couple of changes but for some reason this PR isn't showing up in this remote, only in your one. Don't know why that is. There are also a couple of minor conflicts that need fixing up but hopefully not a big thing.

2021-06-07 13:49 UTC, TheRSP commented
I have now merged in the latest changes from master and removed the redundant use of flexible types. I think this covers everything suggested. Is there anything that is needed?

2021-06-07 14:49 UTC, isaacabraham approved these changes

2021-06-07 14:49 UTC, isaacabraham commented
LGTM - @ninjarobot over to you!

2021-06-08 02:02 UTC, merged