Adding DNS records to existing zones
CompositionalIT/farmer pull request #703
Opened 2021-07-19 16:47 UTC by ninjarobot

The changes in this PR are as follows:

* DNS Zone: Support for adding records to existing zones.

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [x] **Written unit tests** against the modified code that I have made.
* [x] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [x] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

2021-07-19 17:13 UTC, Ryan-Palmer-CIT reviewed
Heya, I had a look over it and it seems fine but I would really get someone else who understands this stuff a bit more than me to check it before merging.

2021-07-20 20:27 UTC, ericsoler1 requested changes
Looks good other than I think I found a bug on the IBuilder.ResourceId for Records

2021-07-20 20:27 UTC, ericsoler1 commented on src/Farmer/Builders/Builders.Dns.fs
> +        member this.ResourceId = zones.resourceId this.Name
Doesnt this need the parent zone when generated the resourceId?

2021-07-20 20:27 UTC, ericsoler1 commented on src/Farmer/Builders/Builders.Dns.fs
> +        member this.ResourceId = zones.resourceId this.Name
Also doesnt this depend on the record type which ResourceId function should be used?

2021-07-20 20:27 UTC, ericsoler1 commented on src/Farmer/Builders/Builders.Dns.fs
> +    [<CustomOperation "link_to_dns_zone">]
Nit: Is there a convention for the name of this operation? I think usually the link_to_dns_zone would imply that its linking to a managed resource and it should take in a IBuilder while link_to_unmanaged_dns_zone would imply that its linking to an externally deployed dns zone.

2021-07-21 10:27 UTC, Thorium commented
This is interesting, as maybe I could get around the current locking problem https://github.com/CompositionalIT/farmer/issues/689#issuecomment-877341371 by deploying the CNAME records manually one-by-one afterwards.

2021-07-21 16:01 UTC, ericsoler1 approved these changes

2021-07-21 16:05 UTC, merged