Cosmosdb serverless
CompositionalIT/farmer pull request #845
Opened 2021-12-12 18:50 UTC by amine-mejaouel

This PR closes #333

Thanks to discussion in #333 and for @dnperfors and @JordanMarr work on the subject, I added the last brick in order to make the serverless work on cosmos db.

The changes in this PR are as follows:

* Update databaseAccounts/* api versions to 2021-04-15
* Add 'serverless' operation to Cosmos builder
  * Using 'serverless' disables previous 'throughput' usages.
  * Likewise, using 'throughput' disables previous 'serverless' usages.cosmosDb 
 ```fsharp
// Per example, the 'throughput' will be ignored, only the 'serverless' will be applied.
cosmosDb {
    name "cosmos-foo"   
    throughput 400<CosmosDb.RU> 
    serverless
}
```
  * Applying 'serverless' in the arm template:
    * adds 'EnableServerless' inside capabitilities
    * adds a location with a location name (without adding it, the template will not work, more details on: #333)

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [ ] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [ ] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [ ] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

Below is a minimal example configuration that includes the new features, which can be used to deploy to Azure:

```fsharp
cosmosDb {
    name "cosmos-foo"
    serverless
}
```

2021-12-18 21:23 UTC, isaacabraham requested changes
Great stuff. I think there's a couple of API surface suggestions that I would like to see that would make the API even more compelling, but the majority of this looks good to go.

2021-12-18 21:23 UTC, isaacabraham commented on src/Farmer/Builders/Builders.Cosmos.fs
> +      DbThroughput : int<RU> option
This will eliminate the need to track two different fields and makes it impossible to accidentally set both Serverless and RUs on.

2021-12-18 21:23 UTC, isaacabraham commented on src/Farmer/Arm/DocumentDb.fs
> +      Serverless : bool
Same as other comment below re: adding a discriminated union.

2021-12-18 21:23 UTC, isaacabraham commented on src/Farmer/Builders/Builders.Cosmos.fs
> +    member __.Serverless(state:CosmosDbConfig) = { state with Serverless = true; DbThroughput = None }
I would consider removing this and overloading the `throughput` keyword to take in the second case of the DU so you could do:

```fsharp
throughput 400<ru>
```

or

```fsharp
throughput Serverless
```

This also works nicely for dynamic scenarios where you want to choose at Farmer runtime what type of DB you want.

2021-12-19 17:21 UTC, amine-mejaouel commented on src/Farmer/Builders/Builders.Cosmos.fs
> +      DbThroughput : int<RU> option
Yes !

2022-01-03 01:03 UTC, isaacabraham commented
Apologies, I need to review the updates.

2022-01-03 01:32 UTC, isaacabraham approved these changes
This is good to go. I made a few tiny tweaks:

* Removing a `when` to a proper pattern match (best practice - pattern matches give better guidance for missing cases).
* Replaced Throughput with FeatureFlag on the Account (correctness - Account doesn't need to know about Throughput, just if Serverless is set or not).
* Renamed ProvisionedThroughput to simply Provisioned.
* Added an example in the docs.

2022-01-03 01:33 UTC, isaacabraham commented
@ninjarobot ok, this is good to go from my side. @amine-mejaouel if you would like to confirm that my final tweaks are ok with you, this can go in. Thanks again!

2022-01-04 20:40 UTC, amine-mejaouel commented
It's all good to me,
Thanks @isaacabraham !

2022-01-04 21:55 UTC, merged